name: musicplayer
description: Music player
version: 0.4.0+2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.0
  sqflite:
  path_provider:
  material_search_bar: ^1.0.0
  url_launcher: 3.0.1
  shared_preferences: ^0.4.2
  http:
  overlay_support: ^1.0.1
  flutter_audio_query:
    git:
      url: https://github.com/shayan4shayan/flutter_audio_query.git
  music_player:
    git:
      url: https://github.com/boyan01/flutter-music-player.git




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/back.jpg
    - images/artist.jpg
    - images/GitHub-Mark.png
    - images/flogo.png
    - images/music.jpg
    - images/instalogo.png
    - images/icon.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
    - family: Quicksand
      fonts:
        - asset: assest/fonts/Quicksand-Medium.ttf
        - asset: assest/fonts/Quicksand-Regular.ttf
    - family: Google Sans
      fonts:
        - asset: assest/fonts/GoogleSans-Regular.ttf

